name: template_2025
description: "A new Flutter project template."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^1.0.8
  rush:
    git:
      url: https://github.com/khaledSayedAbdellah/rush
      ref: "2ff9fce"
  fast_http: ^1.0.6
  go_router: ^7.1.1
  provider: ^6.0.5
  get_it: ^7.6.0
  shared_preferences: ^2.1.1
  photo_view: ^0.14.0
  flutter_screenutil: ^5.7.0
  state_extended: ^5.5.0
  equatable: ^2.0.5
  internet_connection_checker_plus: ^2.0.0
  dartz: ^0.10.1
  http: ^1.0.0
  flutter_svg: ^2.0.5
  intl: ^0.20.1
  google_fonts: ^5.1.0

  # Firebase
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.6.0
  firebase_storage: ^12.0.0
  firebase_database: ^11.0.0
  
  # Google Sign In
  google_sign_in: ^6.2.1
  
  # Google Maps
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  
  # Animations
  lottie: ^2.7.0
  flutter_staggered_animations: ^1.1.1
  
  # Additional utilities
  uuid: ^4.2.1
  cached_network_image: ^3.3.0
  
  # Image and File handling
  image_picker: ^1.0.4
  file_picker: ^8.0.0
  permission_handler: ^11.0.1
  
  # Voice recording
  audioplayers: ^5.2.1
  flutter_sound: ^9.2.13
  
  # Video handling
  video_compress: ^3.1.2
  video_player: ^2.8.2
  
  # Toast messages
  fluttertoast: ^8.2.4
  
  # Location services
  location: ^5.0.3
  
  # File handling
  path_provider: ^2.1.1
  path: ^1.8.3
  
  # URL handling
  url_launcher: ^6.2.2
  
  # File opening
  open_file: ^3.5.0

  
  # App info
  package_info_plus: ^4.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - i18n/
    - assets/
    - assets/icons/
    - assets/animations/
    - assets/images/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.jpeg"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/icon.jpeg"
